spring.application.name=accident
server.port=9090

#spring.data.mongodb.uri=mongodb://localhost:27017/gemini-backend?retryWrites=false
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=gemini-backend

spring.security.user.name=admin
spring.security.user.password=1234

#spring.profiles.active=dev
spring.profiles.active=prod
